# Generated by Django 6.0.5 on 2026-05-29 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('capacity', models.CharField(help_text='e.g. 1.2 kWh, 2.0 kWh', max_length=50)),
                ('purchase_date', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('sold', 'Sold'), ('damaged', 'Damaged'), ('returned', 'Returned')], default='available', max_length=20)),
                ('supplier', models.CharField(max_length=150)),
                ('warranty_years', models.IntegerField(default=3)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batteries', to='branches.inventorylocation')),
            ],
            options={
                'verbose_name_plural': 'Batteries',
                'ordering': ['purchase_date'],
            },
        ),
    ]
