# Generated by Django 5.2.11 on 2026-06-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0002_fifooverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='battery_code',
            field=models.CharField(blank=True, help_text='e.g. BAT-LFP-6030', max_length=100, null=True),
        ),
    ]
