# Generated by Django 6.0.5 on 2026-05-27 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('color_variants', models.JSONField(default=list, help_text='List of available color variants')),
                ('battery_compatibility', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='vehicles.vehiclebrand')),
            ],
            options={
                'unique_together': {('brand', 'model_name')},
            },
        ),
        migrations.CreateModel(
            name='VehicleUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin_number', models.CharField(max_length=50, unique=True)),
                ('motor_number', models.CharField(max_length=50, unique=True)),
                ('chassis_number', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(max_length=50)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('stock_status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('booked', 'Booked'), ('sold', 'Sold'), ('in_transit', 'In Transit'), ('service', 'Service'), ('damaged', 'Damaged')], default='available', max_length=20)),
                ('booking_status', models.BooleanField(default=False)),
                ('assigned_battery', models.CharField(blank=True, help_text='Serial number of assigned battery', max_length=100, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_units', to='branches.branch')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_units', to='branches.inventorylocation')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='vehicles.vehiclemodel')),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_units', to='branches.showroom')),
            ],
        ),
    ]
