# Generated by Django 6.0.5 on 2026-05-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleunit',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleunit',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleunit',
            name='motor_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleunit',
            name='vin_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='vehicleunit',
            constraint=models.UniqueConstraint(condition=models.Q(('vin_number__isnull', False)), fields=('vin_number',), name='unique_vin_when_present'),
        ),
        migrations.AddConstraint(
            model_name='vehicleunit',
            constraint=models.UniqueConstraint(condition=models.Q(('motor_number__isnull', False)), fields=('motor_number',), name='unique_motor_when_present'),
        ),
        migrations.AddConstraint(
            model_name='vehicleunit',
            constraint=models.UniqueConstraint(condition=models.Q(('chassis_number__isnull', False)), fields=('chassis_number',), name='unique_chassis_when_present'),
        ),
    ]
