# Generated by Django 5.1.3 on 2026-07-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicleunit_chassis_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleunit',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='success', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicleunit',
            name='purchase_invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
