declare module 'lucide-react-native' {
  import * as React from 'react';
  import { SvgProps } from 'react-native-svg';

  export interface LucideProps extends SvgProps {
    size?: number | string;
    color?: string;
    strokeWidth?: number | string;
  }

  export type LucideIcon = React.ComponentType<LucideProps>;

  export const Home: LucideIcon;
  export const Landmark: LucideIcon;
  export const ShieldCheck: LucideIcon;
  export const UserCheck: LucideIcon;
  export const TrendingUp: LucideIcon;
  export const Wallet: LucideIcon;
  export const Car: LucideIcon;
  export const Users: LucideIcon;
  export const ChevronRight: LucideIcon;
  export const MapPin: LucideIcon;
  export const ArrowUpRight: LucideIcon;
  export const CheckCircle: LucideIcon;
  export const AlertTriangle: LucideIcon;
  export const CirclePercent: LucideIcon;
  export const Warehouse: LucideIcon;
  export const BatteryCharging: LucideIcon;
  export const Check: LucideIcon;
  export const ShieldAlert: LucideIcon;
  export const UserPlus: LucideIcon;
  export const PhoneCall: LucideIcon;
  export const Award: LucideIcon;
  export const Ban: LucideIcon;
  export const ArrowDownLeft: LucideIcon;
  export const Eye: LucideIcon;
  export const EyeOff: LucideIcon;
  export const Lock: LucideIcon;
  export const User: LucideIcon;
  export const CheckSquare: LucideIcon;
  export const Square: LucideIcon;
  export const Search: LucideIcon;
  export const SlidersHorizontal: LucideIcon;
  export const ChevronDown: LucideIcon;
  export const MoreVertical: LucideIcon;
  export const Zap: LucideIcon;
  export const Gauge: LucideIcon;
  export const Battery: LucideIcon;
  export const Star: LucideIcon;
  export const Sparkles: LucideIcon;
  export const Package: LucideIcon;
  export const Calendar: LucideIcon;
  export const CalendarDays: LucideIcon;
  export const X: LucideIcon;
  export const Layers: LucideIcon;
  export const ShoppingBag: LucideIcon;
  export const ArrowLeft: LucideIcon;
  export const Clock: LucideIcon;
  export const XCircle: LucideIcon;
  export const Plus: LucideIcon;
  export const CheckCircle2: LucideIcon;
  export const Shield: LucideIcon;
  export const CreditCard: LucideIcon;
  export const Phone: LucideIcon;
  export const Tag: LucideIcon;
  export const Save: LucideIcon;
  export const Edit: LucideIcon;
  export const ClipboardCheck: LucideIcon;
  export const Boxes: LucideIcon;
  export const LogOut: LucideIcon;
  export const BadgeCheck: LucideIcon;
  export const BarChart: LucideIcon;
  export const UserX: LucideIcon;
  export const Compass: LucideIcon;
  export const Info: LucideIcon;
  export const Menu: LucideIcon;
  export const Mail: LucideIcon;
  export const Building: LucideIcon;
  export const Settings: LucideIcon;
  export const Settings2: LucideIcon;
  export const FileText: LucideIcon;
  export const IndianRupee: LucideIcon;
  export const Flame: LucideIcon;
  export const Snowflake: LucideIcon;
  export const Sun: LucideIcon;
  export const KeyRound: LucideIcon;
  export const Percent: LucideIcon;
  export const ArrowRight: LucideIcon;
  export const ChevronUp: LucideIcon;
  export const Trash2: LucideIcon;
  export const RotateCcw: LucideIcon;
  export const Truck: LucideIcon;
  export const PackageCheck: LucideIcon;
  export const Bell: LucideIcon;
  export const HelpCircle: LucideIcon;
  export const Globe: LucideIcon;
  export const ScanLine: LucideIcon;
  export const Keyboard: LucideIcon;
  export const PenLine: LucideIcon;
}
