# Generated by Django 6.0.5 on 2026-06-23 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0002_alter_vehicleunit_chassis_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MelaBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=15)),
                ('executive_serial_number', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('battery_type', models.CharField(choices=[('graphene', 'Graphene'), ('Li-24', 'Li-24'), ('Li-30', 'Li-30'), ('Li-40', 'Li-40')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('unconfirmed', 'Unconfirmed Booking'), ('completed', 'Completed & Delivered'), ('cancelled', 'Cancelled')], default='unconfirmed', max_length=20)),
                ('cash_collected', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('sales_executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mela_bookings', to=settings.AUTH_USER_MODEL)),
                ('vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mela_bookings', to='vehicles.vehiclemodel')),
            ],
        ),
        migrations.CreateModel(
            name='MelaInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(help_text='Selected color variant', max_length=50)),
                ('battery_type', models.CharField(choices=[('graphene', 'Graphene'), ('Li-24', 'Li-24'), ('Li-30', 'Li-30'), ('Li-40', 'Li-40')], max_length=20)),
                ('initial_quantity', models.PositiveIntegerField(default=0)),
                ('remaining_quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, help_text='Special campaign price', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mela_inventories', to='vehicles.vehiclemodel')),
            ],
            options={
                'verbose_name_plural': 'Mela Inventories',
                'unique_together': {('vehicle_model', 'color', 'battery_type')},
            },
        ),
    ]
