# Generated by Django 6.0.5 on 2026-06-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mela', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='melabooking',
            name='battery_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='melainventory',
            name='battery_type',
            field=models.CharField(help_text='Battery capacity/spec', max_length=50),
        ),
    ]
