# Generated by Django 5.1.3 on 2026-06-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mela', '0002_alter_melabooking_battery_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MelaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mela_name', models.CharField(default='Grand Monsoon Mela', max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(default='Main Showroom Ground', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Mela Settings',
            },
        ),
    ]
