# Generated by Django 6.0.5 on 2026-06-24 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mela', '0003_melasettings'),
        ('vehicles', '0002_alter_vehicleunit_chassis_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MelaBatteryStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_name', models.CharField(help_text='e.g. 4 battery Graphene', max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Battery component mela price', max_digits=12)),
                ('initial_quantity', models.PositiveIntegerField(default=0)),
                ('remaining_quantity', models.PositiveIntegerField(default=0)),
                ('restock_date', models.DateField(blank=True, help_text='Date when stock is expected to arrive', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Mela Battery Stocks',
            },
        ),
        migrations.AlterModelOptions(
            name='melainventory',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='melainventory',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='melabooking',
            name='battery_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='melabooking',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='melabooking',
            name='vehicle_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mela_bookings', to='vehicles.vehiclemodel'),
        ),
        migrations.AlterField(
            model_name='melainventory',
            name='battery_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='melainventory',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='melainventory',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='melainventory',
            name='vehicle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehiclemodel'),
        ),
        migrations.AddField(
            model_name='melabooking',
            name='mela_battery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='mela.melabatterystock'),
        ),
        migrations.CreateModel(
            name='MelaVehicleStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(help_text='Selected color variant', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, help_text='Vehicle component mela price', max_digits=12)),
                ('initial_quantity', models.PositiveIntegerField(default=0)),
                ('remaining_quantity', models.PositiveIntegerField(default=0)),
                ('restock_date', models.DateField(blank=True, help_text='Date when stock is expected to arrive', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mela_vehicles', to='vehicles.vehiclemodel')),
            ],
            options={
                'verbose_name_plural': 'Mela Vehicle Stocks',
                'unique_together': {('vehicle_model', 'color')},
            },
        ),
        migrations.AddField(
            model_name='melabooking',
            name='mela_vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='mela.melavehiclestock'),
        ),
        migrations.RemoveField(
            model_name='melainventory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='melainventory',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='MelaVehicleBatteryCompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battery_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supported_compatibilities', to='mela.melabatterystock')),
                ('vehicle_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supported_compatibilities', to='mela.melavehiclestock')),
            ],
            options={
                'verbose_name_plural': 'Mela Vehicle Battery Compatibilities',
                'unique_together': {('vehicle_stock', 'battery_stock')},
            },
        ),
    ]
