# Generated by Django 5.1.3 on 2026-06-24 08:40

import django.db.models.deletion
from django.db import migrations, models


def populate_model_names(apps, schema_editor):
    MelaVehicleStock = apps.get_model('mela', 'MelaVehicleStock')
    for stock in MelaVehicleStock.objects.all():
        if stock.vehicle_model:
            stock.model_name = stock.vehicle_model.model_name
            stock.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mela', '0004_melabatterystock_alter_melainventory_options_and_more'),
        ('vehicles', '0002_alter_vehicleunit_chassis_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='melavehiclestock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='melavehiclestock',
            name='model_name',
            field=models.CharField(blank=True, default='', help_text='Typed vehicle name', max_length=100),
        ),
        migrations.AlterField(
            model_name='melavehiclestock',
            name='vehicle_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mela_vehicles', to='vehicles.vehiclemodel'),
        ),
        migrations.RunPython(populate_model_names),
        migrations.AlterUniqueTogether(
            name='melavehiclestock',
            unique_together={('model_name', 'color')},
        ),
    ]

