# Generated by Django 5.1.3 on 2026-06-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mela', '0005_alter_melavehiclestock_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='melabooking',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='mela_proofs/'),
        ),
        migrations.AddField(
            model_name='melabooking',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('bajaj_finance', 'Bajaj Finance')], default='cash', max_length=20),
        ),
    ]
