# Generated by Django 6.0.5 on 2026-06-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mela', '0006_melabooking_payment_proof_melabooking_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='melabooking',
            name='battery_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='melabooking',
            name='charger_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='melabooking',
            name='invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to='mela_invoices/'),
        ),
        migrations.AddField(
            model_name='melabooking',
            name='motor_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='melabooking',
            name='vin_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='melabooking',
            name='status',
            field=models.CharField(choices=[('unconfirmed', 'Unconfirmed Booking'), ('completed', 'Completed'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='unconfirmed', max_length=20),
        ),
    ]
