# Generated by Django 5.1.3 on 2026-07-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mela', '0007_melabooking_battery_no_melabooking_charger_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='melabooking',
            name='payment_details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
