# Generated by Django 6.0.5 on 2026-05-29 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('in_transit', 'In Transit'), ('received', 'Received'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_approved', to=settings.AUTH_USER_MODEL)),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='branches.inventorylocation')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_requested', to=settings.AUTH_USER_MODEL)),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='branches.inventorylocation')),
                ('vehicle_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='vehicles.vehicleunit')),
            ],
        ),
    ]
