# Generated by Django 6.0.5 on 2026-05-29 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('battery', '0001_initial'),
        ('branches', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_contact', models.CharField(max_length=15)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_mode', models.CharField(max_length=50)),
                ('insurance_partner', models.CharField(blank=True, max_length=100, null=True)),
                ('sale_date', models.DateField(auto_now_add=True)),
                ('delivery_status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready for Delivery'), ('delivered', 'Delivered')], default='processing', max_length=20)),
                ('assigned_battery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='battery.battery')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='branches.branch')),
                ('sales_executive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to=settings.AUTH_USER_MODEL)),
                ('vehicle_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='vehicles.vehicleunit')),
            ],
        ),
    ]
