# Generated by Django 5.1.3 on 2026-08-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_salesinvoice_payment_split_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='payment_proof',
            field=models.TextField(blank=True, help_text='Base64 or URL payment receipt image proof', null=True),
        ),
    ]
