# Generated by Django 5.1.3 on 2026-08-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salesinvoice_payment_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='delivery_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready for Delivery'), ('sold', 'Sold (Awaiting Delivery)'), ('delivered', 'Delivered')], default='processing', max_length=20),
        ),
    ]
