# Generated by Django 5.1.3 on 2026-08-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_check_in_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='location_name',
            field=models.CharField(blank=True, default='Workplace Premises', max_length=255),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
