# Generated by Django 5.1.3 on 2026-06-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='manager_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='monthly_target',
            field=models.DecimalField(decimal_places=2, default=15000000.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='branch',
            name='sales_volume',
            field=models.DecimalField(decimal_places=2, default=11200000.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='branch',
            name='target_achieved_pct',
            field=models.IntegerField(default=74),
        ),
        migrations.AddField(
            model_name='branch',
            name='total_stock',
            field=models.IntegerField(default=120),
        ),
    ]
