# Generated by Django 5.1.3 on 2026-07-19 12:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branchcashdeposit_branchexpense_issuereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchcashdeposit',
            name='deposit_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='branchexpense',
            name='expense_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
