# Generated by Django 5.1.3 on 2026-07-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_alter_branchcashdeposit_deposit_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchcashdeposit',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='branchexpense',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='issuereport',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterField(
            model_name='branchexpense',
            name='category',
            field=models.CharField(choices=[('electricity', 'Electricity / Power Bill'), ('transport', 'Vehicle Transport & Delivery'), ('maintenance', 'Showroom Repair & Maintenance'), ('refreshments', 'Staff Refreshments & Water'), ('misc', 'Other Daily Expenses')], default='misc', max_length=30),
        ),
    ]
