# Generated by Django 5.1.3 on 2026-07-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_color_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancebooking',
            name='payment_split_details',
            field=models.JSONField(blank=True, help_text='Split payment breakdown: cash, card, upi, bajaj_finance', null=True),
        ),
    ]
