# Generated by Django 5.1.3 on 2026-08-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_advancebooking_payment_split_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancebooking',
            name='is_advance_booking',
            field=models.BooleanField(default=False),
        ),
    ]
