# Generated by Django 6.0.5 on 2026-05-29 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('ledger_type', models.CharField(choices=[('sales_income', 'Sales Income'), ('purchase_expense', 'Purchase Expense'), ('salary_expense', 'Salary Expense'), ('operational_expense', 'Operational Expense'), ('booking_amount', 'Booking Amount'), ('refund', 'Refund'), ('transfer_expense', 'Transfer Expense')], max_length=30)),
                ('detail', models.TextField()),
                ('income', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('expense', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_mode', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='branches.branch')),
            ],
            options={
                'verbose_name_plural': 'Ledger Entries',
            },
        ),
    ]
