# Generated by Django 5.1.3 on 2026-07-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='payment_split_details',
            field=models.JSONField(blank=True, help_text='Split payment breakdown e.g. {cash: 5000, upi: 3000, bajaj_emi: 2000}', null=True),
        ),
    ]
