# Generated by Django 6.0.5 on 2026-05-29 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('lead_source', models.CharField(choices=[('walk_in', 'Walk-in'), ('website', 'Website'), ('reference', 'Reference'), ('phone', 'Phone Call'), ('social', 'Social Media'), ('other', 'Other')], default='walk_in', max_length=30)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('enquiry', 'Enquiry'), ('new_lead', 'New Lead'), ('contacted', 'Contacted'), ('follow_up', 'Follow-up'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost')], default='new_lead', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_executive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('interested_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='vehicles.vehiclemodel')),
            ],
        ),
    ]
