# Generated by Django 5.2.11 on 2026-06-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
