# Generated by Django 5.1.3 on 2026-08-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_lost_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='advance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_advance_booking',
            field=models.BooleanField(default=False),
        ),
    ]
