# Generated by Django 6.0.5 on 2026-05-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('owner', 'Owner'), ('supervisor', 'Supervisor'), ('sales_executive', 'Sales Executive'), ('sales', 'Sales'), ('staff', 'Operations Staff')], default='sales', max_length=20),
        ),
    ]
