# Generated by Django 5.2.11 on 2026-06-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('owner', 'Owner'), ('supervisor', 'Supervisor'), ('sales_executive', 'Sales Executive'), ('sales', 'Sales'), ('staff', 'Operations Staff'), ('telecaller', 'Telecaller')], default='sales', max_length=20),
        ),
    ]
