# Generated by Django 5.1.3 on 2026-08-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_expo_push_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('owner', 'Owner'), ('supervisor', 'Supervisor'), ('sales_executive', 'Sales Executive'), ('sales', 'Sales'), ('telecaller', 'Telecaller')], default='sales', max_length=20),
        ),
    ]
